# Config for failfast=false
server:
  port: ${appPort:8083}

# RabbitMQ config
rabbitmq:
  host: localhost
  port: 5672
  virtualHost: /
  username: guest
  password: guest
  
  queueNames:
    atlas: atlas-queue
    cms: cms-queue
         